/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as MistakesRouteImport } from './routes/mistakes'
import { Route as PredictedRouteImport } from './routes/predicted'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as MockIndexRouteImport } from './routes/mock/index'
import { Route as MockIdRouteImport } from './routes/mock/$id'
import { Route as PracticeIndexRouteImport } from './routes/practice/index'
import { Route as PracticeUnitRouteImport } from './routes/practice/$unit'
import { Route as ResultsIdRouteImport } from './routes/results/$id'
import { Route as LearnPaperUnitRouteImport } from './routes/learn/$paper.$unit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const MistakesRoute = MistakesRouteImport.update({
  id: '/mistakes',
  path: '/mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictedRoute = PredictedRouteImport.update({
  id: '/predicted',
  path: '/predicted',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockIndexRoute = MockIndexRouteImport.update({
  id: '/mock/',
  path: '/mock/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockIdRoute = MockIdRouteImport.update({
  id: '/mock/$id',
  path: '/mock/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeUnitRoute = PracticeUnitRouteImport.update({
  id: '/practice/$unit',
  path: '/practice/$unit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnPaperUnitRoute = LearnPaperUnitRouteImport.update({
  id: '/learn/$paper/$unit',
  path: '/learn/$paper/$unit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/glossary': typeof GlossaryRoute
  '/methods': typeof MethodsRoute
  '/mistakes': typeof MistakesRoute
  '/predicted': typeof PredictedRoute
  '/progress': typeof ProgressRoute
  '/updates': typeof UpdatesRoute
  '/mock/$id': typeof MockIdRoute
  '/practice/$unit': typeof PracticeUnitRoute
  '/results/$id': typeof ResultsIdRoute
  '/learn/': typeof LearnIndexRoute
  '/mock/': typeof MockIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/learn/$paper/$unit': typeof LearnPaperUnitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/glossary': typeof GlossaryRoute
  '/methods': typeof MethodsRoute
  '/mistakes': typeof MistakesRoute
  '/predicted': typeof PredictedRoute
  '/progress': typeof ProgressRoute
  '/updates': typeof UpdatesRoute
  '/mock/$id': typeof MockIdRoute
  '/practice/$unit': typeof PracticeUnitRoute
  '/results/$id': typeof ResultsIdRoute
  '/learn': typeof LearnIndexRoute
  '/mock': typeof MockIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/learn/$paper/$unit': typeof LearnPaperUnitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exam': typeof ExamRoute
  '/glossary': typeof GlossaryRoute
  '/methods': typeof MethodsRoute
  '/mistakes': typeof MistakesRoute
  '/predicted': typeof PredictedRoute
  '/progress': typeof ProgressRoute
  '/updates': typeof UpdatesRoute
  '/mock/$id': typeof MockIdRoute
  '/practice/$unit': typeof PracticeUnitRoute
  '/results/$id': typeof ResultsIdRoute
  '/learn/': typeof LearnIndexRoute
  '/mock/': typeof MockIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/learn/$paper/$unit': typeof LearnPaperUnitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exam'
    | '/glossary'
    | '/methods'
    | '/mistakes'
    | '/predicted'
    | '/progress'
    | '/updates'
    | '/mock/$id'
    | '/practice/$unit'
    | '/results/$id'
    | '/learn/'
    | '/mock/'
    | '/practice/'
    | '/learn/$paper/$unit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exam'
    | '/glossary'
    | '/methods'
    | '/mistakes'
    | '/predicted'
    | '/progress'
    | '/updates'
    | '/mock/$id'
    | '/practice/$unit'
    | '/results/$id'
    | '/learn'
    | '/mock'
    | '/practice'
    | '/learn/$paper/$unit'
  id:
    | '__root__'
    | '/'
    | '/exam'
    | '/glossary'
    | '/methods'
    | '/mistakes'
    | '/predicted'
    | '/progress'
    | '/updates'
    | '/mock/$id'
    | '/practice/$unit'
    | '/results/$id'
    | '/learn/'
    | '/mock/'
    | '/practice/'
    | '/learn/$paper/$unit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamRoute: typeof ExamRoute
  GlossaryRoute: typeof GlossaryRoute
  MethodsRoute: typeof MethodsRoute
  MistakesRoute: typeof MistakesRoute
  PredictedRoute: typeof PredictedRoute
  ProgressRoute: typeof ProgressRoute
  UpdatesRoute: typeof UpdatesRoute
  MockIdRoute: typeof MockIdRoute
  PracticeUnitRoute: typeof PracticeUnitRoute
  ResultsIdRoute: typeof ResultsIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
  MockIndexRoute: typeof MockIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  LearnPaperUnitRoute: typeof LearnPaperUnitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistakes': {
      id: '/mistakes'
      path: '/mistakes'
      fullPath: '/mistakes'
      preLoaderRoute: typeof MistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predicted': {
      id: '/predicted'
      path: '/predicted'
      fullPath: '/predicted'
      preLoaderRoute: typeof PredictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/': {
      id: '/mock/'
      path: '/mock'
      fullPath: '/mock/'
      preLoaderRoute: typeof MockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/$id': {
      id: '/mock/$id'
      path: '/mock/$id'
      fullPath: '/mock/$id'
      preLoaderRoute: typeof MockIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$unit': {
      id: '/practice/$unit'
      path: '/practice/$unit'
      fullPath: '/practice/$unit'
      preLoaderRoute: typeof PracticeUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$paper/$unit': {
      id: '/learn/$paper/$unit'
      path: '/learn/$paper/$unit'
      fullPath: '/learn/$paper/$unit'
      preLoaderRoute: typeof LearnPaperUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamRoute: ExamRoute,
  GlossaryRoute: GlossaryRoute,
  MethodsRoute: MethodsRoute,
  MistakesRoute: MistakesRoute,
  PredictedRoute: PredictedRoute,
  ProgressRoute: ProgressRoute,
  UpdatesRoute: UpdatesRoute,
  MockIdRoute: MockIdRoute,
  PracticeUnitRoute: PracticeUnitRoute,
  ResultsIdRoute: ResultsIdRoute,
  LearnIndexRoute: LearnIndexRoute,
  MockIndexRoute: MockIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  LearnPaperUnitRoute: LearnPaperUnitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
